/*
 * gencodes.js
 *
 * Copyright (c) 2024 Xiongfei Shi
 *
 * Author: Xiongfei Shi <xiongfei.shi(a)icloud.com>
 * License: Apache-2.0
 *
 * https://github.com/shixiongfei/napi-talib
 */

const fs = require("node:fs");

const loadBinding = () => {
  try {
    return require("./build/Release/napi_talib.node");
  } catch {
    return require("./build/Debug/napi_talib.node");
  }
};

const talib = loadBinding();

const gencodes = () => {
  talib.getFunctions().forEach((funcName) => {
    const funcInfo = talib.explain(funcName);
    console.log(funcInfo);
  });

  return "/* This file is automatically generated by gencodes.js */\n";
};

fs.writeFileSync("functions.ts", gencodes());
